obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-gpiomux.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-keypad.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-mmc.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-storage.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-wifi.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-regulator.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-pmic.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-audio.o
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_SHOOTERU) += board-shooteru-camera.o
endif
obj-$(CONFIG_MACH_SHOOTERU) += display/

